
export const ProductsDATA = [
    {
        id: 1,
        name: 'Ps5 Pulse 3d',
        price: 250000,
        category:'Headset',
        img: 'https://http2.mlstatic.com/D_NQ_NP_939817-MLA49107323113_022022-O.webp',
        description: `Disfruta de una experiencia inalámbrica perfecta con unos auriculares ajustados para audio 3D en las consolas PS5™. Los auriculares inalámbricos PULSE 3D™ tienen un diseño elegante con micrófonos dobles con reducción de ruido, batería recargable integrada y una variedad de controles de fácil acceso.`,
        stock: 5,
    },
    {
        id: 2,
        name: 'Assassin s Creed Valhalla',
        price: 39980,
        category:'Game5',
        img: 'https://http2.mlstatic.com/D_NQ_NP_741777-MLU72630963142_112023-O.webp',
        description: `Con este juego de Assassin's Creed vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 3,
    },
    {
        id: 3,
        name: 'Ea Fc 24',
        price: 34000,
        category:'Game5',
        img:'https://http2.mlstatic.com/D_NQ_NP_937469-MLA72415388833_102023-O.webp',
        description: `EA FC 24 en cuenta primaria, edición estándar para Ps5.`,
        stock: 6,
    },
    {
        id: 4,
        name: 'Auriculares Gamer JBL',
        price: 85499,
        category:'Headset',
        img: "https://http2.mlstatic.com/D_NQ_NP_600188-MLU72700322091_112023-O.webp",
        description: `¡Experimentá la adrenalina de sumergirte en la escena de otra manera! Tener auriculares específicos para jugar cambia completamente tu experiencia en cada partida. Con los JBL 300 no te perdés ningún detalle y escuchás el audio tal y como fue diseñado por los creadores.`,
        stock: 2,
    },
    {
        id: 5,
        name: 'God of War Ragnarök',
        price: 27620,
        category:'Game4',
        img: "https://http2.mlstatic.com/D_NQ_NP_990023-MLA50864327350_072022-O.webp",
        description: `Con este juego de God of War vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 8,
    },
    {
        id: 6,
        name: 'Horizon Forbidden West',
        price: 24000,
        category:'Game5',
        img:'https://http2.mlstatic.com/D_NQ_NP_634562-MLA48799569554_012022-O.webp',
        description: `Con este juego de Horizon vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 7,
    },
    {
        id: 7,
        name: 'Hogwarts Legacy',
        price: 38900,
        category:'Game4',
        img:'https://http2.mlstatic.com/D_NQ_NP_622175-MLA73030174605_112023-O.webp',
        description: `Con este juego de Hogwarts vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 11,
    },
    {
        id: 8,
        name: 'Need for Speed: Heat',
        price: 6800,
        category:'Game4',
        img:'https://http2.mlstatic.com/D_NQ_NP_921424-MLA40931045014_022020-O.webp',
        description: `Con este juego de Need for Speed vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 9,
    },
    {
        id: 9,
        name: 'Sony PlayStation 3',
        price: 250000,
        category:'Console',
        img:'https://http2.mlstatic.com/D_NQ_NP_654507-MLA51356082489_082022-O.webp',
        description: `Con tu consola PlayStation 3 tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.`,
        stock: 11,
    },
    {
        id: 10,
        name: 'Red Dead Redemption 2',
        price: 52999,
        category:'Game4',
        img:'https://http2.mlstatic.com/D_NQ_NP_667696-MLA46792682054_072021-O.webp',
        description: `Ambientado a fines del siglo XIX y comienzos del XX, Red Dead narra la historia del bandido John Marston, quien es chantajeado por agentes federales que además, tienen amenazada a su familia. `,
        stock: 2,
    },
    {
        id: 11,
        name: 'Resident Evil 4 Remake',
        price: 23512,
        category:'Game4',
        img:'https://http2.mlstatic.com/D_NQ_NP_999556-MLA54078260253_022023-O.webp',
        description: `Con este juego de Resident Evil vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.`,
        stock: 3,
    },
    {
        id: 12,
        name: 'Consola Playstation 5',
        price: 1189999,
        category:'Console',
        img:'https://http2.mlstatic.com/D_NQ_NP_974395-MLU72933102575_112023-O.webp',
        description: `Con tu consola PlayStation 5 tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.`,
        stock: 1,
    },
]